# Image 

In [ ]:
from tensorflow import keras
import tensorflow as tf
from tensorflow import keras
import sys
import sklearn
import tensorflow as tf
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import VGG16
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
np.random.seed(42)
import matplotlib.pyplot as plt

In [ ]:
# pip install myutils

In [ ]:
# pip install --upgrade pip

In [ ]:
# pip install tensorflow

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/Shareddrives/ML_Final"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
'animation recommendation.ipynb'
'Combined Model.ipynb'
'content based.ipynb'
'Copy of Music PPT .gslides'
 CSV-CNN.ipynb
 CSV_MLModel.ipynb
 genre-classification-using-parallel-cnn-rnn.ipynb
 HW7.ipynb
'ML PPT.gslides'
 Music_Data
 MusicGenre_csv.ipynb
 MusicGenre_EDA.ipynb
'music genre.gdoc'
 MusicGenre_Image.ipynb
'Recommendation resource.gdoc'


## Data Processing:

In [ ]:
# Apply ImageDataGenerator to make the model robust, also save up on the overhead memory
from keras.preprocessing.image import ImageDataGenerator
train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255.)

In [ ]:
# Build up training data set
train = train_datagen.flow_from_directory('/content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_train',target_size=(300,300),batch_size=32,class_mode='categorical')

Found 799 images belonging to 10 classes.


In [ ]:
train.image_shape

(300, 300, 3)

In [ ]:
train.class_indices

{'blues': 0,
 'classical': 1,
 'country': 2,
 'disco': 3,
 'hiphop': 4,
 'jazz': 5,
 'metal': 6,
 'pop': 7,
 'reggae': 8,
 'rock': 9}

## Classifier Model Build

#### Model 1:

In [ ]:
m1 = keras.Sequential()
m1.add(layers.Conv2D(64, kernel_size=(3,3), input_shape=(300,300,3),activation= "relu"))
m1.add(layers.MaxPooling2D(pool_size=(2,2)))

m1.add(layers.Conv2D(32, kernel_size=(3,3), activation = "relu"))
m1.add(layers.MaxPooling2D(pool_size=(2,2)))

m1.add(layers.Flatten())
m1.add(layers.Dense(units = 64, activation = 'relu'))
m1.add(layers.Dense(units = 10, activation = 'softmax'))

m1.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy']) 

In [ ]:
m1.fit_generator(train, epochs=10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  """Entry point for launching an IPython kernel.


Epoch 1/10
25/25 [==============================] - 126s 5s/step - loss: 2.8929 - accuracy: 0.1214
Epoch 2/10
25/25 [==============================] - 124s 5s/step - loss: 2.1107 - accuracy: 0.2553
Epoch 3/10
25/25 [==============================] - 129s 5s/step - loss: 1.5726 - accuracy: 0.4618
Epoch 4/10
25/25 [==============================] - 127s 5s/step - loss: 0.8849 - accuracy: 0.7209
Epoch 5/10
25/25 [==============================] - 128s 5s/step - loss: 0.3303 - accuracy: 0.9249
Epoch 6/10
25/25 [==============================] - 123s 5s/step - loss: 0.0949 - accuracy: 0.9812
Epoch 7/10
25/25 [==============================] - 123s 5s/step - loss: 0.0338 - accuracy: 0.9962
Epoch 8/10
25/25 [==============================] - 124s 5s/step - loss: 0.0128 - accuracy: 0.9987
Epoch 9/10
25/25 [==============================] - 124s 5s/step - loss: 0.0119 - accuracy: 0.9987
Epoch 10/10
25/25 [==============================] - 125s 5s/step - loss: 0.0132 - accuracy: 0.9975


In [ ]:
m1.save('m1')
print("Saved model")

INFO:tensorflow:Assets written to: m1/assets
Saved model


In [ ]:
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# returns a compiled model
# identical to the previous one
model = load_model('m1')
print("Loaded model from disk")

# test data path
img_dir = "//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test" # Enter Directory of test set

# iterate over each test image
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
files.sort()

# print the files in the dataset_test folder 
for f in files:
    print(f)
    
# make a prediction and add to results 
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (300,300,3))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

Loaded model from disk
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00080.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00081.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00082.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00083.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00084.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00085.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00086.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00087.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00088.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00089.png
//content/drive/Shareddrives/ML_Final/Music_Dat

[array([9]),
 array([0]),
 array([9]),
 array([0]),
 array([3]),
 array([8]),
 array([4]),
 array([8]),
 array([6]),
 array([6]),
 array([4]),
 array([4]),
 array([0]),
 array([6]),
 array([0]),
 array([8]),
 array([0]),
 array([8]),
 array([3]),
 array([0]),
 array([6]),
 array([2]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([2]),
 array([9]),
 array([9]),
 array([9]),
 array([2]),
 array([2]),
 array([4]),
 array([2]),
 array([2]),
 array([0]),
 array([4]),
 array([9]),
 array([6]),
 array([2]),
 array([2]),
 array([5]),
 array([2]),
 array([0]),
 array([2]),
 array([2]),
 array([4]),
 array([4]),
 array([7]),
 array([4]),
 array([4]),
 array([4]),
 array([3]),
 array([9]),
 array([0]),
 array([3]),
 array([3]),
 array([4]),
 array([9]),
 array([3]),
 array([3]),
 array([4]),
 array([8]),

In [ ]:
x = [0,1,2,3,4,5,6,7,8,9]
n = 20
test_label = sorted(x*n)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_label,results)

0.43

#### Model 2:

In [ ]:
m2 = keras.Sequential()
m2.add(layers.Conv2D(64, kernel_size=(3,3), input_shape=(300,300,3),activation= "relu"))
m2.add(layers.MaxPooling2D(pool_size=(2,2)))

m2.add(layers.Conv2D(32, kernel_size=(3,3), activation = "relu"))
m2.add(layers.MaxPooling2D(pool_size=(2,2)))

m2.add(layers.Flatten())
m2.add(layers.Dense(units = 10, activation = 'softmax'))

m2.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy']) 

In [ ]:
m2.fit_generator(train, epochs=10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  """Entry point for launching an IPython kernel.


Epoch 1/10
25/25 [==============================] - 120s 5s/step - loss: 2.7455 - accuracy: 0.1464
Epoch 2/10
25/25 [==============================] - 119s 5s/step - loss: 1.9281 - accuracy: 0.3016
Epoch 3/10
25/25 [==============================] - 119s 5s/step - loss: 1.4896 - accuracy: 0.4743
Epoch 4/10
25/25 [==============================] - 120s 5s/step - loss: 0.9288 - accuracy: 0.7222
Epoch 5/10
25/25 [==============================] - 124s 5s/step - loss: 0.4648 - accuracy: 0.8874
Epoch 6/10
25/25 [==============================] - 131s 5s/step - loss: 0.1752 - accuracy: 0.9750
Epoch 7/10
25/25 [==============================] - 122s 5s/step - loss: 0.0558 - accuracy: 0.9937
Epoch 8/10
25/25 [==============================] - 123s 5s/step - loss: 0.0213 - accuracy: 0.9987
Epoch 9/10
25/25 [==============================] - 126s 5s/step - loss: 0.0110 - accuracy: 0.9987
Epoch 10/10
25/25 [==============================] - 124s 5s/step - loss: 0.0076 - accuracy: 0.9987


In [ ]:
m2.save('m2')
print("Saved model")

INFO:tensorflow:Assets written to: m2/assets
Saved model


In [ ]:
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# returns a compiled model
# identical to the previous one
model = load_model('m2')
print("Loaded model from disk")

# test data path
img_dir = "//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test" # Enter Directory of test set

# iterate over each test image
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
files.sort()

# print the files in the dataset_test folder 
for f in files:
    print(f)
    
# make a prediction and add to results 
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (300,300,3))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

Loaded model from disk
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00080.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00081.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00082.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00083.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00084.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00085.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00086.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00087.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00088.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00089.png
//content/drive/Shareddrives/ML_Final/Music_Dat

[array([8]),
 array([0]),
 array([3]),
 array([3]),
 array([4]),
 array([5]),
 array([4]),
 array([8]),
 array([4]),
 array([1]),
 array([4]),
 array([4]),
 array([1]),
 array([0]),
 array([0]),
 array([5]),
 array([0]),
 array([8]),
 array([3]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([3]),
 array([0]),
 array([2]),
 array([2]),
 array([2]),
 array([8]),
 array([4]),
 array([2]),
 array([2]),
 array([0]),
 array([4]),
 array([0]),
 array([0]),
 array([0]),
 array([2]),
 array([5]),
 array([2]),
 array([5]),
 array([5]),
 array([2]),
 array([4]),
 array([4]),
 array([7]),
 array([4]),
 array([4]),
 array([4]),
 array([0]),
 array([3]),
 array([0]),
 array([3]),
 array([3]),
 array([4]),
 array([4]),
 array([3]),
 array([0]),
 array([4]),
 array([8]),

In [ ]:
x = [0,1,2,3,4,5,6,7,8,9]
n = 20
test_label = sorted(x*n)

from sklearn.metrics import accuracy_score
accuracy_score(test_label,results)

0.44

#### Model 3: 

In [ ]:
m3 = keras.Sequential()
m3.add(layers.Conv2D(64, kernel_size=(3,3), input_shape=(300,300,3),activation= "relu"))
m3.add(layers.MaxPooling2D(pool_size=(2,2)))

m3.add(layers.Flatten())
m3.add(layers.Dense(units = 10, activation = 'softmax'))

m3.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy']) 

In [ ]:
m3.fit_generator(train, epochs=10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  """Entry point for launching an IPython kernel.


Epoch 1/10
25/25 [==============================] - 62s 2s/step - loss: 36.9512 - accuracy: 0.1377
Epoch 2/10
25/25 [==============================] - 65s 3s/step - loss: 1.8354 - accuracy: 0.5432
Epoch 3/10
25/25 [==============================] - 62s 2s/step - loss: 0.5356 - accuracy: 0.9036
Epoch 4/10
25/25 [==============================] - 61s 2s/step - loss: 0.0889 - accuracy: 0.9937
Epoch 5/10
25/25 [==============================] - 63s 3s/step - loss: 0.0228 - accuracy: 0.9987
Epoch 6/10
25/25 [==============================] - 61s 2s/step - loss: 0.0125 - accuracy: 0.9987
Epoch 7/10
25/25 [==============================] - 61s 2s/step - loss: 0.0107 - accuracy: 0.9975
Epoch 8/10
25/25 [==============================] - 61s 2s/step - loss: 0.0090 - accuracy: 0.9987
Epoch 9/10
25/25 [==============================] - 61s 2s/step - loss: 0.0136 - accuracy: 0.9975
Epoch 10/10
25/25 [==============================] - 61s 2s/step - loss: 0.0100 - accuracy: 0.9975


In [ ]:
m3.save('m3')
print("Saved model")

INFO:tensorflow:Assets written to: m3/assets
Saved model


In [ ]:
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# returns a compiled model
# identical to the previous one
model = load_model('m3')
print("Loaded model from disk")

# test data path
img_dir = "//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test" # Enter Directory of test set

# iterate over each test image
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
files.sort()

# print the files in the dataset_test folder 
for f in files:
    print(f)
    
# make a prediction and add to results 
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (300,300,3))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

Loaded model from disk
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00080.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00081.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00082.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00083.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00084.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00085.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00086.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00087.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00088.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00089.png
//content/drive/Shareddrives/ML_Final/Music_Dat

[array([3]),
 array([0]),
 array([3]),
 array([3]),
 array([3]),
 array([0]),
 array([0]),
 array([8]),
 array([2]),
 array([0]),
 array([8]),
 array([4]),
 array([0]),
 array([2]),
 array([0]),
 array([2]),
 array([0]),
 array([2]),
 array([3]),
 array([2]),
 array([1]),
 array([2]),
 array([2]),
 array([1]),
 array([1]),
 array([2]),
 array([5]),
 array([2]),
 array([5]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([5]),
 array([5]),
 array([1]),
 array([2]),
 array([0]),
 array([0]),
 array([2]),
 array([3]),
 array([3]),
 array([3]),
 array([2]),
 array([2]),
 array([2]),
 array([3]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([6]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([4]),
 array([4]),
 array([4]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([3]),
 array([4]),
 array([3]),

In [ ]:
x = [0,1,2,3,4,5,6,7,8,9]
n = 20
test_label = sorted(x*n)

from sklearn.metrics import accuracy_score
accuracy_score(test_label,results)

0.35

#### Model 4:

In [ ]:
m4 = keras.Sequential()
m4.add(layers.Conv2D(64, kernel_size=(3,3), input_shape=(300,300,3),activation= "relu"))
m4.add(layers.MaxPooling2D(pool_size=(2,2)))
m4.add(layers.Conv2D(128, kernel_size=(3,3), activation = "relu"))
m4.add(layers.MaxPooling2D(pool_size=(2,2)))
m4.add(layers.Flatten())

m4.add(layers.Dense(units = 10, activation = 'softmax'))

m4.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy']) 

In [ ]:
m4.fit_generator(train, epochs=10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  """Entry point for launching an IPython kernel.


Epoch 1/10
25/25 [==============================] - 233s 9s/step - loss: 0.0098 - accuracy: 0.9975
Epoch 2/10
25/25 [==============================] - 231s 9s/step - loss: 0.0071 - accuracy: 0.9987
Epoch 3/10
25/25 [==============================] - 220s 9s/step - loss: 0.0089 - accuracy: 0.9987
Epoch 4/10
25/25 [==============================] - 224s 9s/step - loss: 0.0086 - accuracy: 0.9975
Epoch 5/10
25/25 [==============================] - 219s 9s/step - loss: 0.0067 - accuracy: 0.9975
Epoch 6/10
25/25 [==============================] - 219s 9s/step - loss: 0.0069 - accuracy: 0.9975
Epoch 7/10
25/25 [==============================] - 223s 9s/step - loss: 0.0058 - accuracy: 0.9975
Epoch 8/10
25/25 [==============================] - 218s 9s/step - loss: 0.0054 - accuracy: 0.9987
Epoch 9/10
25/25 [==============================] - 217s 9s/step - loss: 0.0059 - accuracy: 0.9975
Epoch 10/10
25/25 [==============================] - 216s 9s/step - loss: 0.0078 - accuracy: 0.9987


In [ ]:
m4.save('m4')
print("Saved model")

INFO:tensorflow:Assets written to: m4/assets
Saved model


In [ ]:
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# returns a compiled model
# identical to the previous one
model = load_model('m4')
print("Loaded model from disk")

# test data path
img_dir = "//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test" # Enter Directory of test set

# iterate over each test image
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
files.sort()

# print the files in the dataset_test folder 
for f in files:
    print(f)
    
# make a prediction and add to results 
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (300,300,3))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

Loaded model from disk
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00080.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00081.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00082.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00083.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00084.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00085.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00086.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00087.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00088.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00089.png
//content/drive/Shareddrives/ML_Final/Music_Dat

[array([9]),
 array([9]),
 array([9]),
 array([3]),
 array([0]),
 array([5]),
 array([0]),
 array([8]),
 array([2]),
 array([4]),
 array([4]),
 array([4]),
 array([0]),
 array([0]),
 array([0]),
 array([8]),
 array([0]),
 array([9]),
 array([0]),
 array([2]),
 array([1]),
 array([2]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([5]),
 array([1]),
 array([5]),
 array([1]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([9]),
 array([3]),
 array([9]),
 array([2]),
 array([2]),
 array([2]),
 array([4]),
 array([2]),
 array([2]),
 array([8]),
 array([4]),
 array([0]),
 array([0]),
 array([0]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([9]),
 array([4]),
 array([4]),
 array([3]),
 array([4]),
 array([4]),
 array([4]),
 array([2]),
 array([9]),
 array([3]),
 array([3]),
 array([3]),
 array([4]),
 array([2]),
 array([3]),
 array([9]),
 array([4]),
 array([8]),

In [ ]:
x = [0,1,2,3,4,5,6,7,8,9]
n = 20
test_label = sorted(x*n)

from sklearn.metrics import accuracy_score
accuracy_score(test_label,results)

0.475

#### Model 5 (VGG16) :

In [ ]:
# Transfer Learning
model=VGG16(include_top=False,input_shape=(300,300,3))

In [ ]:
for layer in model.layers:
    layer.trainable=False

In [ ]:
output=model.layers[-1].output
model_final=tf.keras.layers.Flatten()(output)
model_final=tf.keras.layers.Dense(512,activation='relu')(model_final)
model_final=tf.keras.layers.Dense(64,activation='relu')(model_final)
model_final=tf.keras.layers.Dense(10,activation='softmax')(model_final)
model=tf.keras.models.Model(model.input,model_final)
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit_generator(train,epochs=10)

25/25 [==============================] - 726s 29s/step - loss: 3.1828 - accuracy: 0.2140
Epoch 2/10
25/25 [==============================] - 705s 28s/step - loss: 1.3681 - accuracy: 0.5482
Epoch 3/10
25/25 [==============================] - 703s 28s/step - loss: 0.9987 - accuracy: 0.6884
Epoch 4/10
25/25 [==============================] - 705s 28s/step - loss: 0.8774 - accuracy: 0.7334
Epoch 5/10
25/25 [==============================] - 708s 28s/step - loss: 0.6894 - accuracy: 0.7810
Epoch 6/10
25/25 [==============================] - 729s 29s/step - loss: 0.5812 - accuracy: 0.8123
Epoch 7/10
25/25 [==============================] - 704s 28s/step - loss: 0.6101 - accuracy: 0.8023
Epoch 8/10
25/25 [==============================] - 706s 28s/step - loss: 0.4712 - accuracy: 0.8661
Epoch 9/10
25/25 [==============================] - 714s 29s/step - loss: 0.3573 - accuracy: 0.8949
Epoch 10/10
25/25 [==============================] - 716s 29s/step - loss: 0.2735 - accuracy: 0.9299


In [ ]:
## Save model
model.save('model.h')
print('Saved model')

INFO:tensorflow:Assets written to: model.h/assets
Saved model


In [ ]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 300, 300, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 300, 300, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 300, 300, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 150, 150, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 150, 150, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 150, 150, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 75, 75, 128)       0   

In [ ]:
# returns a compiled model
# identical to the previous one
model = load_model('model.h')
print("Loaded model from disk")

# test data path
img_dir = "//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test" # Enter Directory of test set

# iterate over each test image
data_path = os.path.join(img_dir, '*g')
test = glob.glob(data_path)
test.sort()

# print the files in the dataset_test folder 
for f in test:
    print(f) 
    
# make a prediction and add to results 
data = []
results = []
for f1 in test:
    img = image.load_img(f1, target_size = (300,300))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

Loaded model from disk
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00080.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00081.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00082.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00083.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00084.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00085.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00086.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00087.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00088.png
//content/drive/Shareddrives/ML_Final/Music_Data/Music_Genre_Data/images_test/blues00089.png
//content/drive/Shareddrives/ML_Final/Music_Dat

[array([2]),
 array([0]),
 array([2]),
 array([2]),
 array([0]),
 array([5]),
 array([5]),
 array([0]),
 array([5]),
 array([0]),
 array([0]),
 array([2]),
 array([0]),
 array([5]),
 array([0]),
 array([2]),
 array([5]),
 array([2]),
 array([2]),
 array([2]),
 array([1]),
 array([5]),
 array([5]),
 array([1]),
 array([1]),
 array([2]),
 array([2]),
 array([1]),
 array([5]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([5]),
 array([1]),
 array([5]),
 array([1]),
 array([5]),
 array([1]),
 array([2]),
 array([2]),
 array([0]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([2]),
 array([0]),
 array([2]),
 array([2]),
 array([2]),
 array([0]),
 array([2]),
 array([5]),
 array([0]),
 array([0]),
 array([0]),
 array([2]),
 array([0]),
 array([0]),
 array([0]),
 array([2]),
 array([2]),
 array([2]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [ ]:
# check category labels in training_set
train.class_indices

{'blues': 0,
 'classical': 1,
 'country': 2,
 'disco': 3,
 'hiphop': 4,
 'jazz': 5,
 'metal': 6,
 'pop': 7,
 'reggae': 8,
 'rock': 9}

In [ ]:
x = [0,1,2,3,4,5,6,7,8,9]
n = 20
test_label = sorted(x*n)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_label,results)

0.245